### ISSUE TITLE
Better Testing.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#2639]
- [ ] Shore Up Function Coverage by Adding More Testing
  - [ ] Prioritize the Least Covered Portions of Code First
  - [ ] Adding Tests May or May Not Involve Refactoring the Tests and/or Source
  - [ ] Add Scripts for Beefier Scale Tests (Cactus + VG) to be Run Every 1 to 2 Month(s)
  - [ ] Create or Post Existing User-Friendly Tutorials on Cactus and VG in the Toil Docs
  - [ ] Look at Long Running Tests and See if They Can't Be Made Shorter
  - [ ] Delete Redundant Tests

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/TOIL-6)
┆Issue Number: TOIL-6
