### ISSUE TITLE
CWL v1.1 support

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#2714]
CWL v1.1 was [recently announced](https://groups.google.com/forum/#!topic/common-workflow-language/TGX7xPzgFcs).

@DailyDreaming is it just a matter of updating the [cwltool version](https://github.com/DataBiosphere/toil/blob/master/setup.py#L37) and ensuring tests pass? I don't think any of the new features affect the internal Toil/CWL integration.

 - [ ] Test [213/253] Test WorkflowStepInput.loadContents
  - https://github.com/common-workflow-language/cwltool/pull/694/commits/2f9cbdb3a0aa1bd965dd951c7a55bfc3061b47e7
 - [ ] Test [227/253] Test requirements in input document via EnvVarRequirement
 - [ ] Test [228/253] Test conflicting requirements in input document via EnvVarRequirement and expression
 - [ ] Test [229/253] Test conflicting requirements in input document via EnvVarRequirement
 - [ ] Test [242/253] Test that default behavior is 'no_listing' if not specified
 - [ ] Test [244/253] Test that 'listing' is not present when loadListing on input parameter is 'no_listing'
 - [ ] Test [246/253] Test that 'listing' is present in top directory object but not subdirectory object when loadListing on input parameter loadListing is 'shallow_listing'

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-384)
┆Issue Number: TOIL-384

**Comment by mr-c** [comment]
FYI, the new conformance tests for v1.1 are at https://github.com/common-workflow-language/cwl-v1.1

**Comment by DailyDreaming** [comment]
@arostamianfar Yes, it's generally that straight forward.  Sorry for the late reply, I had a long trip to the UK.

**Comment by arostamianfar** [comment]
Thanks for the pointers! Ran the tests, but there were some failures:

```
227 tests passed, 13 failures, 13 unsupported features

Failed tests:
Test [100/253] Test required, optional and null secondaryFiles on array of files.
Test [200/253] Test secondaryFiles on anonymous record fields
Test [201/253] Test secondaryFiles on SchemaDefRequirement record fields
Test [203/253] Test secondaryFiles propagation through workflow
Test [210/253] Test WorkflowInputParameter.inputBinding.loadContents
Test [211/253] Test WorkflowInputParameter.loadContents
Test [213/253] Test WorkflowStepInput.loadContents
Test [227/253] Test requirements in input document via EnvVarRequirement
Test [228/253] Test conflicting requirements in input document via EnvVarRequirement and expression
Test [229/253] Test conflicting requirements in input document via EnvVarRequirement
Test [242/253] Test that default behavior is 'no_listing' if not specified
Test [244/253] Test that 'listing' is not present when loadListing on input parameter is 'no_listing'
Test [246/253] Test that 'listing' is present in top directory object but not subdirectory object when loadListing on input parameter loadListing is 'shallow_listing'
```
Detailed results: [toil-cwl-1.1-results.txt](https://github.com/DataBiosphere/toil/files/3390575/toil-cwl-1.1-results.txt)


Also, should we have conformance tests for both v1.0 and v1.1 or just having v1.1 pass is enough?

**Comment by DailyDreaming** [comment]
@arostamianfar I think we need support for v1.0 as well as v1.1.

@mr-c How does cwltool handle this?

**Comment by mr-c** [comment]
@DailyDreaming we test `cwltool` against both the `v1.0` and `v1.1` conformance tests suites

**Comment by mr-c** [comment]
The CWL v1.1 conformance tests are located at https://github.com/common-workflow-language/cwl-v1.1

@DailyDreaming

**Comment by SpheMakh** [comment]
@mr-c is there an ETA on this. We really need the `InplaceUpdateRequirement` feature to scale up our pipeline.

**Comment by DailyDreaming** [comment]
@SpheMakh Starting work on this this week.  We'll see how much work there is and update as support is added until done.

**Comment by mr-c** [comment]
2020-06-09 update: 7 tests are failing: 213,236,242,243,244,245,246
